version: '3'

services:
  php:
    image: yiisoftware/yii-php:8.0-fpm
    working_dir: /app
    restart: unless-stopped
    volumes:
      - ./:/app

  nginx:
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - ./public:/app/public
      - ./data/nginx/:/etc/nginx/conf.d/
    depends_on:
      - php
    restart: unless-stopped
